/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CustomerRouteRouteImport } from './routes/customer/route'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as AuthSelectRoleRouteImport } from './routes/auth/select-role'
import { Route as AuthWorkspaceRouteImport } from './routes/auth/workspace'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as CustomerBookingsRouteImport } from './routes/customer/bookings'
import { Route as CustomerDishesRouteImport } from './routes/customer/dishes'
import { Route as CustomerFavoritesRouteImport } from './routes/customer/favorites'
import { Route as CustomerMapRouteImport } from './routes/customer/map'
import { Route as CustomerProfileRouteImport } from './routes/customer/profile'
import { Route as RestaurantAdminRouteImport } from './routes/restaurant/admin'
import { Route as RestaurantKitchenRouteImport } from './routes/restaurant/kitchen'
import { Route as AuthCustomerLoginRouteImport } from './routes/auth/customer/login'
import { Route as AuthCustomerSignupRouteImport } from './routes/auth/customer/signup'
import { Route as AuthRestaurantLoginRouteImport } from './routes/auth/restaurant/login'
import { Route as AuthRestaurantSignupRouteImport } from './routes/auth/restaurant/signup'
import { Route as CustomerRestaurantRestaurantIdRouteImport } from './routes/customer/restaurant.$restaurantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSelectRoleRoute = AuthSelectRoleRouteImport.update({
  id: '/auth/select-role',
  path: '/auth/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWorkspaceRoute = AuthWorkspaceRouteImport.update({
  id: '/auth/workspace',
  path: '/auth/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerBookingsRoute = CustomerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerDishesRoute = CustomerDishesRouteImport.update({
  id: '/dishes',
  path: '/dishes',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerFavoritesRoute = CustomerFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerMapRoute = CustomerMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const RestaurantAdminRoute = RestaurantAdminRouteImport.update({
  id: '/restaurant/admin',
  path: '/restaurant/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantKitchenRoute = RestaurantKitchenRouteImport.update({
  id: '/restaurant/kitchen',
  path: '/restaurant/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCustomerLoginRoute = AuthCustomerLoginRouteImport.update({
  id: '/auth/customer/login',
  path: '/auth/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCustomerSignupRoute = AuthCustomerSignupRouteImport.update({
  id: '/auth/customer/signup',
  path: '/auth/customer/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRestaurantLoginRoute = AuthRestaurantLoginRouteImport.update({
  id: '/auth/restaurant/login',
  path: '/auth/restaurant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRestaurantSignupRoute = AuthRestaurantSignupRouteImport.update({
  id: '/auth/restaurant/signup',
  path: '/auth/restaurant/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRestaurantRestaurantIdRoute =
  CustomerRestaurantRestaurantIdRouteImport.update({
    id: '/restaurant/$restaurantId',
    path: '/restaurant/$restaurantId',
    getParentRoute: () => CustomerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRoute
  '/auth/select-role': typeof AuthSelectRoleRoute
  '/auth/workspace': typeof AuthWorkspaceRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/dishes': typeof CustomerDishesRoute
  '/customer/favorites': typeof CustomerFavoritesRoute
  '/customer/map': typeof CustomerMapRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/restaurant/admin': typeof RestaurantAdminRoute
  '/restaurant/kitchen': typeof RestaurantKitchenRoute
  '/customer/': typeof CustomerIndexRoute
  '/auth/customer/login': typeof AuthCustomerLoginRoute
  '/auth/customer/signup': typeof AuthCustomerSignupRoute
  '/auth/restaurant/login': typeof AuthRestaurantLoginRoute
  '/auth/restaurant/signup': typeof AuthRestaurantSignupRoute
  '/customer/restaurant/$restaurantId': typeof CustomerRestaurantRestaurantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRoute
  '/auth/select-role': typeof AuthSelectRoleRoute
  '/auth/workspace': typeof AuthWorkspaceRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/dishes': typeof CustomerDishesRoute
  '/customer/favorites': typeof CustomerFavoritesRoute
  '/customer/map': typeof CustomerMapRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/restaurant/admin': typeof RestaurantAdminRoute
  '/restaurant/kitchen': typeof RestaurantKitchenRoute
  '/customer': typeof CustomerIndexRoute
  '/auth/customer/login': typeof AuthCustomerLoginRoute
  '/auth/customer/signup': typeof AuthCustomerSignupRoute
  '/auth/restaurant/login': typeof AuthRestaurantLoginRoute
  '/auth/restaurant/signup': typeof AuthRestaurantSignupRoute
  '/customer/restaurant/$restaurantId': typeof CustomerRestaurantRestaurantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRoute
  '/auth/select-role': typeof AuthSelectRoleRoute
  '/auth/workspace': typeof AuthWorkspaceRoute
  '/customer/bookings': typeof CustomerBookingsRoute
  '/customer/dishes': typeof CustomerDishesRoute
  '/customer/favorites': typeof CustomerFavoritesRoute
  '/customer/map': typeof CustomerMapRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/restaurant/admin': typeof RestaurantAdminRoute
  '/restaurant/kitchen': typeof RestaurantKitchenRoute
  '/customer/': typeof CustomerIndexRoute
  '/auth/customer/login': typeof AuthCustomerLoginRoute
  '/auth/customer/signup': typeof AuthCustomerSignupRoute
  '/auth/restaurant/login': typeof AuthRestaurantLoginRoute
  '/auth/restaurant/signup': typeof AuthRestaurantSignupRoute
  '/customer/restaurant/$restaurantId': typeof CustomerRestaurantRestaurantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/admin'
    | '/kitchen'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/super-admin'
    | '/auth/select-role'
    | '/auth/workspace'
    | '/customer/bookings'
    | '/customer/dishes'
    | '/customer/favorites'
    | '/customer/map'
    | '/customer/profile'
    | '/restaurant/admin'
    | '/restaurant/kitchen'
    | '/customer/'
    | '/auth/customer/login'
    | '/auth/customer/signup'
    | '/auth/restaurant/login'
    | '/auth/restaurant/signup'
    | '/customer/restaurant/$restaurantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/kitchen'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/super-admin'
    | '/auth/select-role'
    | '/auth/workspace'
    | '/customer/bookings'
    | '/customer/dishes'
    | '/customer/favorites'
    | '/customer/map'
    | '/customer/profile'
    | '/restaurant/admin'
    | '/restaurant/kitchen'
    | '/customer'
    | '/auth/customer/login'
    | '/auth/customer/signup'
    | '/auth/restaurant/login'
    | '/auth/restaurant/signup'
    | '/customer/restaurant/$restaurantId'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/admin'
    | '/kitchen'
    | '/login'
    | '/signup'
    | '/sitemap.xml'
    | '/super-admin'
    | '/auth/select-role'
    | '/auth/workspace'
    | '/customer/bookings'
    | '/customer/dishes'
    | '/customer/favorites'
    | '/customer/map'
    | '/customer/profile'
    | '/restaurant/admin'
    | '/restaurant/kitchen'
    | '/customer/'
    | '/auth/customer/login'
    | '/auth/customer/signup'
    | '/auth/restaurant/login'
    | '/auth/restaurant/signup'
    | '/customer/restaurant/$restaurantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRouteRoute: typeof CustomerRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperAdminRoute: typeof SuperAdminRoute
  AuthSelectRoleRoute: typeof AuthSelectRoleRoute
  AuthWorkspaceRoute: typeof AuthWorkspaceRoute
  RestaurantAdminRoute: typeof RestaurantAdminRoute
  RestaurantKitchenRoute: typeof RestaurantKitchenRoute
  AuthCustomerLoginRoute: typeof AuthCustomerLoginRoute
  AuthCustomerSignupRoute: typeof AuthCustomerSignupRoute
  AuthRestaurantLoginRoute: typeof AuthRestaurantLoginRoute
  AuthRestaurantSignupRoute: typeof AuthRestaurantSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/select-role': {
      id: '/auth/select-role'
      path: '/auth/select-role'
      fullPath: '/auth/select-role'
      preLoaderRoute: typeof AuthSelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/workspace': {
      id: '/auth/workspace'
      path: '/auth/workspace'
      fullPath: '/auth/workspace'
      preLoaderRoute: typeof AuthWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/bookings': {
      id: '/customer/bookings'
      path: '/bookings'
      fullPath: '/customer/bookings'
      preLoaderRoute: typeof CustomerBookingsRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/dishes': {
      id: '/customer/dishes'
      path: '/dishes'
      fullPath: '/customer/dishes'
      preLoaderRoute: typeof CustomerDishesRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/favorites': {
      id: '/customer/favorites'
      path: '/favorites'
      fullPath: '/customer/favorites'
      preLoaderRoute: typeof CustomerFavoritesRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/map': {
      id: '/customer/map'
      path: '/map'
      fullPath: '/customer/map'
      preLoaderRoute: typeof CustomerMapRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/restaurant/admin': {
      id: '/restaurant/admin'
      path: '/restaurant/admin'
      fullPath: '/restaurant/admin'
      preLoaderRoute: typeof RestaurantAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/kitchen': {
      id: '/restaurant/kitchen'
      path: '/restaurant/kitchen'
      fullPath: '/restaurant/kitchen'
      preLoaderRoute: typeof RestaurantKitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/customer/login': {
      id: '/auth/customer/login'
      path: '/auth/customer/login'
      fullPath: '/auth/customer/login'
      preLoaderRoute: typeof AuthCustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/customer/signup': {
      id: '/auth/customer/signup'
      path: '/auth/customer/signup'
      fullPath: '/auth/customer/signup'
      preLoaderRoute: typeof AuthCustomerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/restaurant/login': {
      id: '/auth/restaurant/login'
      path: '/auth/restaurant/login'
      fullPath: '/auth/restaurant/login'
      preLoaderRoute: typeof AuthRestaurantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/restaurant/signup': {
      id: '/auth/restaurant/signup'
      path: '/auth/restaurant/signup'
      fullPath: '/auth/restaurant/signup'
      preLoaderRoute: typeof AuthRestaurantSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/restaurant/$restaurantId': {
      id: '/customer/restaurant/$restaurantId'
      path: '/restaurant/$restaurantId'
      fullPath: '/customer/restaurant/$restaurantId'
      preLoaderRoute: typeof CustomerRestaurantRestaurantIdRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
  }
}

interface CustomerRouteRouteChildren {
  CustomerBookingsRoute: typeof CustomerBookingsRoute
  CustomerDishesRoute: typeof CustomerDishesRoute
  CustomerFavoritesRoute: typeof CustomerFavoritesRoute
  CustomerMapRoute: typeof CustomerMapRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerRestaurantRestaurantIdRoute: typeof CustomerRestaurantRestaurantIdRoute
}

const CustomerRouteRouteChildren: CustomerRouteRouteChildren = {
  CustomerBookingsRoute: CustomerBookingsRoute,
  CustomerDishesRoute: CustomerDishesRoute,
  CustomerFavoritesRoute: CustomerFavoritesRoute,
  CustomerMapRoute: CustomerMapRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerRestaurantRestaurantIdRoute: CustomerRestaurantRestaurantIdRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperAdminRoute: SuperAdminRoute,
  AuthSelectRoleRoute: AuthSelectRoleRoute,
  AuthWorkspaceRoute: AuthWorkspaceRoute,
  RestaurantAdminRoute: RestaurantAdminRoute,
  RestaurantKitchenRoute: RestaurantKitchenRoute,
  AuthCustomerLoginRoute: AuthCustomerLoginRoute,
  AuthCustomerSignupRoute: AuthCustomerSignupRoute,
  AuthRestaurantLoginRoute: AuthRestaurantLoginRoute,
  AuthRestaurantSignupRoute: AuthRestaurantSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
